version: 2
updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - "npm"
      - "dependencies"
      - "need-review"
      - "frontend"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    assignees:
      - "gbowne1"
      - "manuel12"
      - "pawel975"
    reviewers:
      - "gbowne1"
      - "manuel12"
      - "pawel975"
  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - "npm"
      - "dependencies"
      - "need-review"
      - "backend"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    assignees:
      - "gbowne1"
      - "manuel12"
      - "pawel975"
    reviewers:
      - "gbowne1"
      - "manuel12"
      - "pawel975"
  - package-ecosystem: npm
    directory: "/e2e"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    labels:
      - "npm"
      - "dependencies"
      - "need-review"
      - "e2e"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    assignees:
      - "gbowne1"
      - "manuel12"
      - "pawel975"
    reviewers:
      - "gbowne1"
      - "manuel12"
      - "pawel975"
